name: i4d
channels:
  - conda-forge
  # - pytorch-nightly
dependencies:
  - PyOpenGL==3.1.0
  - trimesh
  - numpy
  - pandas
  - plyfile
  # - pytorch
  - tensorboard
  # - kaolin # install from source
  - pip
  - pip:  
    - mesh-to-sdf