name: nise
channels:
  - pytorch
  - nvidia
  - anaconda
  - defaults
dependencies:
  - python=3.8.5
  - pytorch=2.0.1=py3.8_cuda11.7_cudnn8_0
  - numpy
  - tensorboard
  - pyyaml
  - scikit-image
  - plyfile
  - pip
  - pip:
    - open3d
    - kaolin